---
title: "RCT"
output: html_document
---

```{r}
library(tidyverse)
mail<-read_csv("http://www.minethatdata.com/Kevin_Hillstrom_MineThatData_E-MailAnalytics_DataMiningChallenge_2008.03.20.csv")
```
```{r}
male_df<-mail%>%
  filter(segment !="Womens E-Mail")%>%
  mutate(treatment=ifelse(segment=="Mens E-Mail",1,0))
```
```{r}
summary_by_segment<-male_df%>%
  group_by(treatment)%>%
  summarise(conversion_rate =mean(conversion),
            spend_mean =mean(spend),
            count=n())

summary_by_segment
```
```{r}
mens_mail<-male_df%>%
  filter(treatment==1)%>%
  pull(spend)

no_mail<-male_df%>%
  filter(treatment==0)%>%
  pull(spend)

t.test(mens_mail,no_mail)
```
```{r}
set.seed(1)
obs_rate_c<-0.5
obs_rate_t<-0.5

biased_date<-male_df%>%
  mutate(obs_rate_c=ifelse(
    (history>300)|(recency<6)|(channel=="Multichannel"),obs_rate_c,1
  ),
  obs_rate_t=ifelse(history>300|(recency<6)|(channel=="Multichannel"),1,obs_rate_t),
  rondom_number=runif(n=NROW(male_df)))%>%
  filter((treatment==0&rondom_number<obs_rate_c)|
           treatment==1&rondom_number<obs_rate_t)

summary_by_segment_biased<-biased_date%>%
  group_by(treatment)%>%
  summarise(cvr=mean(conversion),
            spend_mean=mean(spend),
            count=n())
summary_by_segment_biased

mens_mail_biased<-biased_date%>%
  filter(treatment==1)%>%
  pull(spend)
no_mail_biased<-biased_date%>%
  filter(treatment==0)%>%
  pull(spend)

glimpse(no_mail_biased)
t.test(mens_mail_biased,no_mail_biased)
```


